### ISSUE TITLE
Visual Studio 2019 Manage Extensions Will not Update Codist

### ISSUE THREAD

**Issue by dchay** [wmjordan/Codist#136]
Thank you for this awesome product!

Current Issue:
VS says there is a Codist Update.
I am currently on 5.8.0.6032,
The update is for 5.8.0.6038.
Click Update and close VS.

VSIX Installer Dialog
---------------------------
This extension is already installed to all applicable products.
---------------------------
OK   
---------------------------

Reopen VS.
VS still says there is a Codist Update.

Thank you for your help,
Game Daddy Daniel

**Comment by wmjordan** [comment]
The 6032 is the beta version (internal version was still 5.7).
6038 is the public release (internal version 5.8).

When Codist detects the internal version is updated (ordinary users do not download beta versions), it will display a notice bar on TOP of the code window for once. So ordinary users can get to know that some things are changed, hopefully :)
The next time you open VS, it will not appear again.

**Comment by bddckr** [comment]
I think there is an actual issue here, though.

1. I check for updates in VS.
![image](https://user-images.githubusercontent.com/294347/97159258-e166ed00-177a-11eb-98af-de5927c350ea.png)
2. I allow it to update by downloading right now already.
3. VS tells me I need to restart VS to install the update.
4. I close VS and as always the VSIX installer pops up, but this time it immediately shows this error message.
![image](https://user-images.githubusercontent.com/294347/97159205-cf854a00-177a-11eb-8b04-144313521995.png)
5. I open up VS and it still shows the old version is installed. I can repeat this process multiple times - at this step we always are back to step 1 basically.

**Comment by wmjordan** [comment]
That's really weird.
There's no logic in Codist preventing the version update.
Please try uninstalling Codist and reinstall it.

Are you using VS 2019 Preview?

**Comment by wmjordan** [comment]
That's really weird.
I experienced this as well when I installed the beta and tried to update to the latest release via the extension manager.

**Comment by wmjordan** [comment]
I found that the pkgdef within the vsix file was still 5.7.
That should be something wrong with the packer.

I will check it a bit later.

Thank you for reporting this.

**Comment by wmjordan** [comment]
I unpacked the VSIX downloaded from the extension web site and verified that it was actually version 5.7.

Somehow the VS extension management page went wrong, which updated the version number and other metadata information but the VSIX was kept unchanged.

I've republished a new version on to the extension web site and it should work properly now.

**Comment by bddckr** [comment]
It worked!
![image](https://user-images.githubusercontent.com/294347/97201751-1b53e580-17b3-11eb-9096-67da17453176.png)

Thank you for this fix and all the great work on this awesome extension!

**Comment by dchay** [comment]
AWESOME!!!

**Comment by wmjordan** [comment]
Thank you for keeping an eye on Codist :)
