### ISSUE TITLE
Feature Request: separate highlight options for braces and parentheses

### ISSUE THREAD

**Issue by bozonsky** [wmjordan/Codist#147]
It would be great to switch parentheses and braces highlight separately, because it can help emphasize "if"/"for"/etc statements.

It doesn't help much when braces and parentheses are both highlighted, because nothing stands out. Also braces have their innate structural accent, so parentheses benefit more from being distinctly colored.

![image](https://user-images.githubusercontent.com/26069060/107529235-3ffe8c80-6bed-11eb-9723-94d31d179d7e.png)

**Comment by wmjordan** [comment]
Thank you for the suggestion.
I can not see the problem _when braces and parentheses are both highlighted, because nothing stands out_.
I personally set different colors for branch braces and loop braces. Their colors are different enough.
Braces and parentheses are different characters, they have different shapes. Why _nothing stands out_?

![image](https://user-images.githubusercontent.com/12182730/107598586-3a3e9080-6c59-11eb-9618-1d68089e8e58.png)

**Comment by bozonsky** [comment]
Thanks for screenshot, your logic obviously makes sense, but many people, myself included, try to keep highlight minimalistic.
In case when I only want to find logic statements of branches, I don't need braces to be also highlighted.

![image](https://user-images.githubusercontent.com/26069060/107826412-72f47c00-6db7-11eb-985e-e5c00d1b721e.png)

Also, technically, curly braces are not totally "belong" to loops or branches, so I want to emphasize that in my color scheme.

**Comment by wmjordan** [comment]
Technically it is nothing difficult.
But adding these options will affect existing user experiences.
Thus I need more feedback from other users to get on.
