### ISSUE TITLE
Allow variant FontTypefaces of a FontFamily in Advanced Syntax Highlighting

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#200]
Could you please make it so that all font variants are explicitly listed in Codist's font dropdown list as well?

_Originally posted by @fitdev in https://github.com/wmjordan/Codist/issues/197#issuecomment-1134310141_

**Comment by wmjordan** [comment]
@fitdev
It is possible to do so, yet quite a few places have to be changed.

**Comment by fitdev** [comment]
I think it would be nice, because:
- Usually all text should be rendered in the same font for aesthetic reasons
- Yet it may be desirable to use different variants of a font family because simply changing the style (to bold for example) may not be the same thing as using a bolder variant - these are different and look different.

But if it requires much work, put in a backlog. I managed to edit setting in Json config file directly. In fact, I guess the reason for VS crash when selecting the font was probably because the font variant name was not in the dropdown list.

**Comment by wmjordan** [comment]
Oops, it is the same as #195
