### ISSUE TITLE
Highlight members that implement a particular interface

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#221]
It would be nice if you can implement the following:

1. Range `..` operator should be treated as operator and not as punctuation.
2. Add a category for _implemented_ members, i.e. members that implement a particular interface (implicitly, but perhaps also include explicit implementations too). On the Interfaces themselves members that have DIMs should also be in this category (after all they are implemented too).

**Comment by wmjordan** [comment]
> 1. Range `..` operator should be treated as operator and not as punctuation.

The range `DotDotToken` being classified as `punctuation` is done by Roslyn. I think they are correct.
Operators does something to the values.
Punctuations don't.
The DotDotToken in the range expression is used to annotate that is a range, thus it is a punctuation.


> 2\. Add a category for _implemented_ members, i.e. members that implement a particular interface

Unfortunately, this will be too slow.
You can take a look at the [implementation of corresponding function in Super Quick Info](https://github.com/wmjordan/Codist/blob/f720e8b48c9d45380b20b5ac1039d15872696eec/Codist/QuickInfo/CSharpQuickInfo.cs#L988-L1032). There are a lot of calculations in that method. We have to find out all interfaces that the containing type of the symbol in question then match the signature of each type members--first by symbol kind, then accessibility (don't take that interface members are all `public` and instantial, there are `private` or `static` ones from C# 8 on), then name, and finally the slowest signature match. Doing this `O(n)` operation in Super Quick Info is acceptable, since the calculation takes milliseconds and comparatively much faster than showing up the Quick Info window. However, when doing so on each symbol when syntax highlighting, the performance will probably be unacceptably too slow.

**Comment by wmjordan** [comment]
The implementations of `INamedTypeSymbol` interface in Roslyn has a maybe-optimized overload of `GetMembers(name)`. Using that overload instead of iterating results from `GetMembers()` may be a little bit faster--it depends on whether other components or Roslyn consumers have called that overload with `(name)` before. However, highlighting members that implement any interface is still slow.

**Comment by fitdev** [comment]
I see. Thank you for your detailed explanations.

I understand that `..` is considered punctuation by Roslyn, though personally I would prefer ti to be highlighted same as operator, as to me it "acts" on 1 or 2 operands (numbers) and produces a new type (range). But I guess it's a matter of preference.

I did not realize that interface implementation lookup is so costly. Of course then it makes sense to only make it available for Super Quick Info. But if there would be a fast way to do it, it would be really nice. But I agree, not at the cost of performance.
