### ISSUE TITLE
Suggestion: Super Quick Info group separators

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#244]
Hello! Big fan of your extension, it's a wonderful tool.

I'm wondering if it would be possible to add an option for Super Quick Info groups to be visually separated similar to this style:
![image](https://user-images.githubusercontent.com/1366970/222300003-d1da8ffd-90ea-415f-9def-45e49461bd4e.png)

It looks this way because I am using your extension combined with Enhanced ToolTips from ReSharper (which unfortunately is conflicting with Super Quick Info in the sense that it doesn't allow interacting with it).

**Comment by wmjordan** [comment]
Hi, @IneedHelp you are welcome.

@fitdev, could you take the trouble commenting on this.

**Comment by fitdev** [comment]
I am not 100% sure what exactly is meant by @IneedHelp , but if _borders / extra padding_ is what is meant, then personally I do not think it's a good idea to do it in _all_ logical sections, as it will lead to too much visual distraction in some cases (like too many horizontal lines / rectangles). It may make sense to perhaps add just horizontal line separators to visually split the tooltip into header, body, and footer (although how these sections should be defined is up to one's preference).

On a related note about information presentation in Super Quick Infos, perhaps the _returns_ subsection of the signature of a member can be improved by including information about `ref` and `readonly` / `readonly ref` variants (right now this information is not shown at all) - perhaps by simply listing those keywords before the return type name. If a member is using `yield return` as opposed to `return` perhaps that too can be included.

**Comment by wmjordan** [comment]
Thank you for your comments, @fitdev.
The borders and horizontal line have brought similar feelings to me.

As for the `ref` stuff, it is already displayed in the signature part. There's no need to redundantly display it in the `returns` section.
<img width="404" alt="image" src="https://user-images.githubusercontent.com/12182730/222358149-717ccb0e-0fda-45ec-9992-24476582b0ad.png">

**Comment by fitdev** [comment]
Yes, sorry. I should have clarified. I meant moving the `ref` part to the "returns" section, so you would have there: `<returns icon> ref int` and above it you would have just `... static method` (no `ref` there).

**Comment by wmjordan** [comment]
> moving the `ref` part to the "returns" section

Hmm, it is reasonable to do so.
<img width="394" alt="image" src="https://user-images.githubusercontent.com/12182730/222379819-22b9772d-bac6-4399-87a0-6654c1c6ff0a.png">

**Comment by IneedHelp** [comment]
I admit that there's redundant "sections/rectangles" presented in the screenshot, but that's due to the mixing of ReSharper's EnhancedToolTip with Codist's Super Quick Info, but what I really meant is the option of introducing some sort of separation between major sections or very distinct sections of the presented information.

**Comment by wmjordan** [comment]
> some sort of separation between major sections or very distinct sections of the presented information

Margins between sections are the separations.
I've tried. The lines distracted me without bringing any benefit beyond the margins.

Maybe we can dim some icons within the sections.
So, you can quickly tell the start of a section by the icons with negative indentation.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/12182730/222428909-89462e22-945d-4a45-88f5-b6ad243c004d.png">

**Comment by fitdev** [comment]
Personally, I don't like the dimming. Perhaps indentation by 1 icon space would be better? But then I am ok with the current presentation.

**Comment by IneedHelp** [comment]
I am aware that the way information is presented is very much a matter of preference, that's why I suggested this addition as an _option_ users choose to enable. I should say that many of my preferences are tightly tied to Enhanced ToolTips which I've been using on top of Codist for years, and now making the decision to ditch Enhanced ToolTips, I get a brain itch whenever I notice the differences. Similarly to @fitdev , I wouldn't use the dimming (although that could represent an option for someone who does or might); I particularly like the dashed line/border for section separation:
![image](https://user-images.githubusercontent.com/1366970/222448448-a41cd7e2-4897-407c-9d3f-925982e16fbf.png)

**Comment by wmjordan** [comment]
> Perhaps indentation by 1 icon space would be better?

It may be, but it takes time to implement.

> I particularly like the dashed line/border for section separation

I've already tried that. I don't like so many lines there.

On the contrary to #216, which triggered my same pain when working with the Quick Info and eventually I made up my mind to redesign the representation from scratch with @fitdev and @laicasaane (in #214), actually I am feeling OK with the current implementation, thus I don't want to take any time to change it at this moment.

I am dealing with the nasty #227 which turns out to be unfixed, which may frustrate some users. And #245 is more worthy of investigation.

**Comment by DimitarCC** [comment]
> I've already tried that. I don't like so many lines there.

I think  its a matter of preference...
You can add an option to have or not have the separation lines. So everybody will be happy.
For me current look is quite tight and sometimes i am lost in the text.
So i also think is better if you can add separation lines.

**Comment by wmjordan** [comment]
I am sorry that I can not come up with a better design.
After quite some attempts, I have to give up again.

If anyone has a better idea, please post it here. A conceptual screenshot will be nice.

**Comment by wmjordan** [comment]
> Perhaps indentation by 1 icon space would be better?

@fitdev I just tried that. It does not look good to me. It wasted some display space.

**Comment by DimitarCC** [comment]
@wmjordan 

I understand that you want to show up as much info as possible in the tooltip. But please understand that much info is not usable if you can not read it.

So i made a little draft how i would do it...

![image](https://user-images.githubusercontent.com/1904901/229039981-d4db557c-95f1-4fde-ae26-aa5d87a5625b.png)

![image](https://user-images.githubusercontent.com/1904901/229040063-755ba09d-599f-4d64-86c2-b4fe8a184f2b.png)

So
1. The main icon should be few pixels down on the same level as the first line of text
2. The informational section should be down and rows in it should have separation between them
3. There should be separation between parameters and their information. Also indentation should be the same. I know this will lost some space but in my opinion it is much readable. I would made it with   •   instead of :. Its much more visually readable.
4. Is it possible this icon to be changed to exhamation or to be used different icons depending on the severity of the issue?

![image](https://user-images.githubusercontent.com/1904901/229045743-a11a6edf-88fa-4898-9bcf-f19c1120fadd.png)


Regarding the identation inside sections...I have several proposals
1. With a buble around the header so to identify the start of the section

![image](https://user-images.githubusercontent.com/1904901/229043136-b41ba976-4ad1-4b8b-b5eb-4a0e76161dd3.png)

2. Without icons for the members of the section. (we all know that childs of the section are from same type. like interfaces)

![image](https://user-images.githubusercontent.com/1904901/229044042-02aad567-e89e-40a7-ad7f-25cd31d31dac.png)

3. With smalled icon for the childs and slight indentation

![image](https://user-images.githubusercontent.com/1904901/229045344-28fec2f4-a4af-466c-bf27-2aa780795ae7.png)

Finally, i want to say that you did great work. I appreciate it but it have to be adjusted. Also i just propose things. it is not mandatory to do it. Also all of my proposals can be made optional with settings.

**Comment by fitdev** [comment]
@wmjordan 
> I just tried that. It does not look good to me. It wasted some display space.
I agree. Current design seems better.

**Comment by wmjordan** [comment]
> However maybe some horizontal spacing between major sections may be increased a bit (by a few pixels).

@fitdev 
Thanks for your comment. It has brighten the way ahead!
Fortunately, this is technically possible and seems easy to implement. I will give it a try.



> For me is very difficult to read because different sections are too near

@DimitarCC 
Well, as @fitdev has remarked above, I will try to see whether it is possible to widen the distance between sections.

> 4\. Is it possible this icon to be changed to exhamation or to be used different icons depending on the severity of the issue?

#37 has a long discussion on this. And the current implementation is the best I can do.

**Comment by DimitarCC** [comment]
> @wmjordan
> 
> > I just tried that. It does not look good to me. It wasted some display space.
> 
> I agree. Current design seems better.

For me is very dificult to read because different sections are too near. No only major sections.
All is matter of personal preference. Not all think the same as you. So thats why i said to be made as configurable options.

> > However maybe some horizontal spacing between major sections may be increased a bit (by a few pixels).
> 
> @fitdev Thanks for your comment. It has brighten the way ahead! Fortunately, this is technically possible and seems easy to implement. I will give it a try. <img alt="image" width="268" src="https://user-images.githubusercontent.com/12182730/229069922-07e5fa05-5e3d-4121-94cb-d2209a1e87fd.png"> Versus current implementation below: <img alt="image" width="260" src="https://user-images.githubusercontent.com/12182730/229070757-e0ba005c-d257-4192-b5cd-63933bbd6c59.png">
> 
> > For me is very difficult to read because different sections are too near
> 
> @DimitarCC Well, as @fitdev has remarked above, I will try to see whether it is possible to widen the distance between sections.
> 
> > 4. Is it possible this icon to be changed to exhamation or to be used different icons depending on the severity of the issue?
> 
> #37 has a long discussion on this. And the current implementation is the best I can do.

Please make more space also between description and returns and so on.
That is too near and when is large description text and returns description is dificult to distinguish between them.

**Comment by wmjordan** [comment]
> what is required to build the extension myself?

In stall the Visual Studio Extension Development workload will do.
However, the project in this repository is supposed to be working with VS 2017 through VS 2022, thus the project targets .NET Framework 4.6.1.

> So if you point me out what i need to build this and when in the code to look for the UI stuff i can try to modify this myself and see how it will look.

The Quick Info hacking code is in QuickInfo\QuickInfoOverrider.cs.
Find the OnVisualParentChanged method of UIOverrider where the magic begins.

**Comment by DimitarCC** [comment]
@wmjordan 
Thanks. Will give it a try.

**Comment by wmjordan** [comment]
The XML Doc part is done by the OverrideDocumentation method in QuickInfo\CSharpQuickInfo.cs.

If you are unhappy with the `returns` being to closed to the `summary`, you should head to the above method and jump to the RenderXmlDoc method in Helpres\XmlDocRenderer.cs.

**Comment by fitdev** [comment]
Perhaps, there could be 2 styles for Super Quick Infos to accommodate users with varying preferences: the current one (called default / condensed), and the new one (with more space around different sections)?

Another thing, sorry to mention it here, as it is not related to the issue, but regarding the XML Docs in Super Quick Infos, is it possible to render _member symbols_ in a distinguished style from the rest of the text and _prefix them with their containing type_:

`Please see <see cref="DateTime.Now" />` currently is rendered as `Please see Now`, while ti would be nice to have it rendered as `Please see DateTime.Now` instead (with both `DateTime` and `Now` parts clickable).

**Comment by wmjordan** [comment]
> Perhaps, there could be 2 styles for Super Quick Infos to accommodate users with varying preferences: the current one (called default / condensed), and the new one (with more space around different sections)?

Hmm, it is possible.
However, a demonstration of the "more space" version will be nice before I get start on it.

> prefix them with their containing type

Technically, it is easy to implement that.
In less than 0.1%'s time, I need that too, and I hover on the symbol and I will see the name of the containing type. I have no memory that I want to click on the containing type instead of the member.
For the rest 99.9%'s time, I don't want that prefix since it wastes space and appears distractive.

**Comment by fitdev** [comment]
> For the rest 99.9%'s time, I don't want that prefix since it wastes space and appears distractive.

My case is the opposite, as I work with literally 1000s of different types that may have _same member names_, and I cannot possibly remember which type a particular member likely refers too. So, perhaps this should be an option. Also, VS's default behavior is to show the containing type.

**Comment by wmjordan** [comment]
> My case is the opposite, as I work with literally 1000s of different types that may have _same member names_, and I cannot possibly remember which type a particular member likely refers too. So, perhaps this should be an option. Also, VS's default behavior is to show the containing type.

OK. It is reasonable.
The behavior of VS's Quick Info is a pain for me.

If the member has the same containing type as the current member, should the containing type still be displayed?

**Comment by DimitarCC** [comment]
@wmjordan 
That is much better.  Thanks.

**Comment by DimitarCC** [comment]
Regarding diagnostics classification there is diagnostics service in roslyn that can be get from workspace. GetService(...). Cant you use that to get property the analyzers issues?

**Comment by wmjordan** [comment]
There's an new beta for download.

**Comment by wmjordan** [comment]
This issue will be closed as improvements have been done to the recent beta versions.
