### ISSUE TITLE
[Feature request] automatically close brackets and quotes even when no text is selected

### ISSUE THREAD

**Issue by BachiMjavanadze** [wmjordan/Codist#272]
Please add in your extention the ability to automatically close brackets even when no text is selected. 

`Automatic brace completion` does not works properly in `Visual Studio IDE`:

![vs-img](https://user-images.githubusercontent.com/38082501/177119702-30aa879e-9691-4c1f-90b0-1233a12bb815.gif)

but `VSCode` does this job correctly:

![vscode-gif](https://user-images.githubusercontent.com/38082501/177119735-5bab40c0-0376-4484-9610-bf88c6cde552.gif)

I would disable `Visual Studio IDE` standard behavior:

![image](https://user-images.githubusercontent.com/38082501/177114618-d3f948bf-bd55-4da1-9d5b-3969ffd34dc9.png)

and enable your extension's option. I suggest to add into settings one more option:

`AutomaticalyCloseAnyBraces: true/false`

enabling this option should cause automatically close open braces: (), {}, []

mouse cursor should be between braces: (**|**), {**|**}, [**|**]

to avoid incorrect behavior angle brackets should not auto close:

`if(a<>b)`

P.S. Please do it also for double quotes `"|"` and single quotes `'|'`

**Comment by wmjordan** [comment]
The situation is somewhat complicated.
Kind of alike #198, I guess.

**Comment by wmjordan** [comment]
I studied the behavior of the auto-completion of parentheses in VS Code.
It always completes the right part of the parentheses pair.
VS will check the next character to the caret, if it is the right parenthesis, it won't automatically add the right parenthesis.
However, adding the ")" by hand is not so difficult since our finger is already on top of the "(".

It is not easy for Codist to add the ")" since it is unpredictable whether Codist or VS will complete the parentheses pair first.
It can lead to a situation that both of them inserts the ")" and a duplicated ")" certainly sucks. Maybe you should push the VS guy more.

**Comment by BachiMjavanadze** [comment]
@wmjordan I did it: [Auto Close & Surround Punctuations](https://marketplace.visualstudio.com/items?itemName=BachiMjavanadze.AutoCloseAndSurroundPunctuations). Fill free to include it to your extension

**Comment by wmjordan** [comment]
Interesting!
I have trouble visiting the extension website. Do you host your extension on Github?

**Comment by BachiMjavanadze** [comment]
@wmjordan 
https://github.com/BachiMjavanadze/AutoCloseAndSurroundPunctuations
