### ISSUE TITLE
Bug: NavBar Draws Wrong Accessibility Icons for Partial Types

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#53]
A tiny bug that has to do with accessibility icons for partial types in the NavBar:

**file1.cs**

`public partial class Foo { }`

NavBar shows *public* accessibility icon, which is *correct*.

**file2.cs**

`partial class Foo { }`

NavBar shows *internal* accessibility icon, which is *wrong*. It should show public (since the type (class) is still public).

**Comment by wmjordan** [comment]
This issue could not be solved efficiently.
The partial type allows putting its accessibility modifier in another file. Unfortunately, the worst case is that Roslyn has to scan the whole project to find that "another file", which is inefficient, especially when you open a solution and VS is busy loading the code files. No one will love to wait the NaviBar there simply in order to let it figure out the right icon.

I'll use another icon for partial types without accessibility modifier in the next version.

**Comment by fitdev** [comment]
Absolutely, I agree. Performance should come first!
