### ISSUE TITLE
More Keyboard Shortcuts for NaviBar

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#77]
The planned keyboard shortcuts for NaviBar:

- [x] Up/Down/PageUp/PageDown in the filter box will change the selected symbol, accordingly.
- [x] Moving between adjacent menus (shortcut key not determined yet)
- [x] Esc: dismiss the menu and go back to the editor
- [x] Ctrl+\` twice: drop down the search definitions menu
- [x] Ctrl+1 twice: drop down the search type members menu

From Hernan Torrez in MarketPlace:

I just wish I could use the navigation bar with the keyboard alone. Like pressing Ctrl+F2 to open the drop down, then pressing TAB (or the cursor keys) to move to the buttons on the right side, pressing DOWN to open the lists, etc.

**Comment by evanricard** [comment]
wmjordan, I was just about to make a suggestion for this but it looks like someone already beat me to it less than 24 hours ago! I would gladly be willing to pay for such a feature. 

Thanks!

**Comment by wmjordan** [comment]
@evanricard Thanks for participating this discussion. Although I am _mousoholic_ , periodically I still work with the keyboard and this suggestion does not seem too difficult to implement, comparing with the others here. Hopefully it will be implemented soon.

**Comment by wmjordan** [comment]
@evanricard I'd just made a new version to drop down menus from the navigation bar.
1. Focus on the editor.
2. Double hit Ctrl+\` to bring out the search definition menu; double hit Ctrl+1 to search members in the active class.

Those hotkeys can be reassigned via the global _Keyboard_ section in the _Options_ page.

@fantasyz Please give me some feedback about this feature modification, if you have time.

[Codist.zip](https://github.com/wmjordan/Codist/files/3107681/Codist.zip)

**Comment by fantasyz** [comment]
Just gave it a try and found a little issues. 
1.  [PgUp] & [PgDn] key is not working on search member list. Only Up/Down arrow keys works.
2. When cancel a search by pressing ESC, the focus is still on a button on the NaviBar UI. Does not return to the text editor. Thus, I cannot use other shortcuts like [Ctrl+,] but have to press ESC again to completely leave Navi Bar.
3. If mouse cursor is already on the list area, when opening the search UI, it would interrupt the typing (lost focus on the textbox by the mouse when the list update).

**Comment by wmjordan** [comment]
Thank you for the feedback!

1. Could you share your suggestions about the behavior of the paging keys?
2. It is really an annoyance. I will see whether it is possible to return the focus to the editor.
3. I feel this issue the most annoying among these three. Currently it is incurable unless I develop some controls to replace the NaviBar menu.

**Comment by fantasyz** [comment]
For the page up/down keys, I think you could reference how the current native [Ctrl+,] work. When focus is on the typing search box, page up/ down should behave like Up/Down arrow key but move like 10-15 items at a time instead of one.

I can imagine issue #3 is not easy to fix if things are mostly builtin by the UI components. 
Maybe add a bool flag to check whether the list is under construction and disable the mouse events on the items during those update moments?

**Comment by wmjordan** [comment]
It seems that your point 1 and point 3 are actually a same issue :(

The following build solved the Esc issue.
[Codist.zip](https://github.com/wmjordan/Codist/files/3112495/Codist.zip)

**Comment by evanricard** [comment]
I've also just tried the extension; I started by typing the shortcut, Ctrl + ` (backtick) - and it didn't work :)! What is the name of the functionality in the keyboard options to change the binding?

**Comment by wmjordan** [comment]
Hi, @evanricard please hit the _Ctrl+\`_ shortcut TWICE within a second--I planned to add more shortcuts in the future, so I changed _Ctrl+\`_ to _Ctrl+\`, Ctrl+\`_. Maybe there will be some more _Ctrl+\` followed by something else_ combinations later.
And the _Ctrl+1, Ctrl+1_ shortcut works only when you place the caret within a type since it is used to search type member definitions.

I'd also love to hear your advice on shortcuts.

The function names for the above shortcut keys are _Search Declaration_ and _Search Class Member_, respectively. You can see them in the _Edit/Find and Replace_ menu.

There is also a known issue that those shortcut keys won't be available until a C# project is fully loaded and parsed in VS 2017. However, you can click the corresponding _NaviBar_ menu items with your mouse. It is quite weird to me, but I could not find a way to fix that at this moment.

For the amount of donation, you can use the following link, where you can type any number as you like within it: https://www.paypal.me/wmzuo/

Thank you very much for your enthusiasm!

**Comment by evanricard** [comment]
Excellent! I had to readjust my particular keybind for Edit.SearchDeclaration because it actually wasn't even bound to anything when I installed it on my machine possibly due to conflicting keybinds with or something I'm not sure. Before checking to see if they keybind was actually bound, I had actually tried running the commands in the Command Window and the Edit.GoToFindCombo box that you can add to the toolbar to run commands without opening up the command window. 

I noticed some strange behavior doing this, which, is odd, because the menu commands seem to work just fine. I managed to crash Visual Studio a couple of times running the commands without pressing the keybinds - I can send you a video of me doing this or something if you'd like. 

For instance, when running Edit.SearchClassMember when not actually on a "member" through the command combo-box would make the application hang or crash or running Edit.SearchDeclaration would shoot me all the way back to the top of the document wherever the namespace declaration might be. 
Reiterating, the keyboard shortcuts and the menu commands seem to work fine - thanks for the addition to the extension! 

![image](https://user-images.githubusercontent.com/30779615/56742345-8fd34180-6742-11e9-8d38-a8cc6bc40a69.png)

**Comment by wmjordan** [comment]
Thank you for your thorough tests.
I am sorry for the crashes, since I use my mouse all the time and never use the command window.
I tried to execute the NaviBar commands via the _Search Visual Studio_ box, nothing bad occurred.

To troubleshoot the crashes, please open the Windows **Event Viewer** and jump to the **Application** logs and find out something with source = **.NET Runtime** where you can find the stack traces for the crashes. Please post the stack trace so I can track it down.

**Comment by evanricard** [comment]
Sure thing, will check it out as soon as I can tomorrow. Thanks again.

Contact Info:
LinkedIn: https://www.linkedin.com/in/evanricard/
Github: https://github.com/evanricard
Portfolio: evanricard.com (Temporarily down, working on an alternative!)

**Comment by evanricard** [comment]
Hey again wmjordan,

I’ve looked through the entirety of logs that have been produced in the last 24 hours:

"Source Information”

.NET Runtime - Error Code 1022 
“Loading profiler failed”. Failing pretty much every every minute of the day…probably not related.

Windows Error Reporting – Error Code 1001
Events tied to VisualStudioNonFatalErrors2, PerfWatsonVS12Data, MoAppHang, WinSetupDiag02…not really sure if any of that is useful either.

Application Error – Error Code 1000 
Faulting application name: devenv.exe, version: 16.0.28803.156, time stamp: 0x5ca7f459
Faulting module name: KERNELBASE.dll, version: 10.0.18356.1, time stamp: 0xc121897b
Exception code: 0xe0434352

Application Hang – Error Code 1002 
- The program SearchUI.exe version 10.0.18356.1 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 1ae0

The program WindowsInternal.ComposableShell.Experiences.TextInput.InputApp. version 10.0.18356.1 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 5180
 Start Time: 01d4fc4439245a78
 Termination Time: 4294967295
 Application Path: C:\Windows\SystemApps\InputApp_cw5n1h2txyewy\WindowsInternal.ComposableShell.Experiences.TextInput.InputApp.exe
 Report Id: 8f5afa94-ab5a-4fa2-bd1c-7b335b3cf279
 Faulting package full name: InputApp_1000.18356.1.0_neutral_neutral_cw5n1h2txyewy
 Faulting package-relative application ID: App
 Hang type: Navigation

--- Lots of stuff in between that don’t really seem relevant like Bonjour Service or “Informational logging” ---

I am not sure if any of that helped – let me know if I can do anything else for you! 

Is there any way I can attach the debugger in VSCode to devenv.exe (or whatever the process name is for Visual Studio) and then try to debug it that way? 

Thanks! 
Evan

Contact Info:
LinkedIn: https://www.linkedin.com/in/evanricard/
Github: https://github.com/evanricard
Portfolio: evanricard.com (Temporarily down, working on an alternative!)

**Comment by wmjordan** [comment]
I am sorry that the above stuff does not help.

You might try to reproduce the crash, then open the Event Viewer, jump to the **Application** logs and find something with source is **.NET Runtime**.
The most recently crash should produce an entry at the top as soon as you open it.

**Comment by evanricard** [comment]
No worries, I can’t seem to reproduce it! I will let you know if it happens again. Perhaps it was just a result of working with too many different programs/extensions and not enough hardware…not sure!

Contact Info:
LinkedIn: https://www.linkedin.com/in/evanricard/
Github: https://github.com/evanricard
Portfolio: evanricard.com (Temporarily down, working on an alternative!)

**Comment by wmjordan** [comment]
Please turn to me and post the stack trace if the crash reoccurs.

**Comment by evanricard** [comment]
Hey Jordan, I'm getting more crashes. I really have not opened Visual Studio since we last spoke so I am unsure if this is the result of working with another extension I just downloaded today. 

I think I can replicate the issue on demand but I'll need you to post a picture of exactly where in the Event Viewer you want me to find the crash log. Thanks.

**Comment by wmjordan** [comment]
![捕获](https://user-images.githubusercontent.com/12182730/57667870-d6c4a080-7637-11e9-8587-04cd93a8a819.PNG)

In the events viewer, first locate the _Applications_ on the left, and then find the _.NET Runtime_ on the top, the stack trace for the crash will be shown at the bottom.

**Comment by evanricard** [comment]
`Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Windows.Controls.Primitives.Popup.OnWindowResize(System.Object, System.Windows.AutoResizedEventArgs)
   at System.Windows.Interop.HwndSource.Resize(System.Windows.Size)
   at System.Windows.Interop.HwndSource.OnLayoutUpdated(System.Object, System.EventArgs)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Media.MediaContext.Resize(System.Windows.Media.ICompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)`

**"Search Class Member"** is also non-existent for me today in the Edit menu and I am no _longer able to find_ the command itself in the keyboard shortcuts menu.

**Comment by wmjordan** [comment]
It seems that the crash was not related to Codist. The following methods have something to do with window resizing, which is not subscribed by the NaviBar.

> System.Windows.Media.MediaContext.Resize(System.Windows.Media.ICompositionTarget) at
> System.Windows.Interop.HwndTarget.OnResize() at 

What version of VS are you using?

**Comment by wmjordan** [comment]
Could you try to disable some extensions and see whether the crash still occurs?

**Comment by wmjordan** [comment]
@fantasyz 
The recently released Codist had solved the issue you listed above.

Please give it a try.
All features on this request have been implemented in the latest commit.
Please open a new issue if you have some new ideas or suggestions.

@evanricard 
I could not reproduce the crash you reported and I would close this issue now. Please open one if you can provide solid evidence that Codist is related to your crash.
