### ISSUE TITLE
Members inside nested regions are not listed on NaviBar

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#95]
Using Codist 5.2, some members are not show in the NaviBar:

```csharp
public class Outer {
	#region REGION_OUTER
		public class Inner {
			public int SomeMemberInInnerClass() => 0; //<- Does not appear on NaviBar at all.
			#region REGION_INNER
				public int SomeMemberInInnerClassInnerRegion() => 0; //<- Does not appear on NaviBar at all.
			#endregion
		}
	#endregion
}
```

**Comment by wmjordan** [comment]
I could not reproduce this.
![shot](https://user-images.githubusercontent.com/12182730/60498859-f1d39880-9ce9-11e9-8a9c-1b2f0d65bbb1.png)

Could you post a screenshot?

**Comment by fitdev** [comment]
Actually in my concrete case the outer type was a `struct` but I did not think it would make any difference:

![2019-07-02 15_50_55-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/60514234-bb921b00-9ce1-11e9-9e85-5353850424c1.jpg)

**Comment by wmjordan** [comment]
It is by design.
Members in the nested class `Names` are only displayed under the `Names` item ON the Navi Bar, as my screenshot shows.
They will not appear in the enclosing class `ByteSize`, otherwise it will cause confusion.
Regions, since they do not belong to the syntax tree of types and members, will be displayed even when they are in the nested type.

**Comment by fitdev** [comment]
You are right. Sorry about that. I forgot that this not only applies to types within a namespace within the same file, but also to nested types.
