### ISSUE TITLE
Drag & Drop Members Between Partial Types in Navi Bar Could Crash VS

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#99]
If a type have several partial files, dragging and dropping members in Navigation Bar between those files could cause VS to crash.

@fitdev, have you ever met with this problem?

**Comment by fitdev** [comment]
Not yet, but I have not really tested this feature thoroughly. In fact, now that I tried it, I noticed that as I drag an item towards the bottom of the list it begins scrolling really fast (basically entire screen at a time). I would prefer it to be slower, and, if possible, support for mouse wheel, so that as you are dragging an item, you can use mouse wheel to scroll the list down.

**Comment by wmjordan** [comment]
Thank you for giving the feedback.

I experienced the crash and made a fix for this issue and your problem.
[Codist.zip](https://github.com/wmjordan/Codist/files/3433804/Codist.zip)

**Comment by fitdev** [comment]
Thank you! Seems to work fine on my end - does not crash VS, and the scroll speed is much better now. Still, would be great if mouse-wheel could be supported to, as well as clearer insertion markers (perhaps done as top/bottom border changes of the items being dragged over).

**Comment by wmjordan** [comment]
The mouse-wheel, unfortunately, can not be implemented.
We never see any application supports mouse-wheel scrolling.
The insertion markers may be possible.
